---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: traefikee
  name: traefik-enterprise-static-config
data: 
  static.yaml: | 
    entryPoints:
      web:
        address: ":80"
        http:
          redirections:
            entryPoint:
              to: websecure
              scheme: https
              permanent: true
      websecure:
        address: ":443"
 
    api:
      dashboard: true
    
    apiportal:
      path: spec.json
     
    providers:
      kubernetescrd: {}
      kubernetesingress: {}
      
    certificatesResolvers:
      cloudflare:
        acme:
          email: <YOUR_EMAIL>
          storage: acme.json
          dnsChallenge:
            provider: cloudflare
            resolvers:
              - "1.1.1.1"
 